spring:
  datasource:
    url: jdbc:h2:file:./data/demo;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
file:
  upload:
    storage-path: ./uploads
